### ISSUE TITLE
Return empty() when possible

### ISSUE THREAD

**Issue by briancavalier** [mostjs/core#152]
See #150 

There quite a few operations where if at least one input stream is empty(), the operation will always return a stream containing zero events. In such cases, some operations return the canonical empty(), and some don't.

It might be interesting to always return the canonical empty() in those cases. That would allow empty() to annihilate other operations more effectively. It trades some up-front cost for reduction in cpu and memory later when a stream is observed.

### Operations that could return empty()

* [x] `map`
* [x] `filter`
* [x] `ap`
* [x] `loop`
* [x] `withItems` & `zipItems` (previously implemented)
* [x] `zip` & `zipArray`
* [x] `combine` & `combineArray`
* [x] `mergeMapConcurrently`, and thus `join`, `chain`, and `concatMap`
* [x] `snapshot` & `sample` (#186)
* [x] `skipRepeats` & `skipRepeatsWith`
* [x] `slice`, `take`, `skip`
* [x] `takeWhile`
* [x] `skipWhile`
* [x] `skipAfter`
* ~`withLocalTime`~ - end time still needs to be localized, so `withLocalTime` can't be annihilated by `empty()`
* [x] `awaitPromises`
* [x] `switchLatest`
* [x] `throttle`
* [x] `debounce`
* [x] `merge(empty(), empty())` and `mergeArray` when all streams are `empty()`
* [x] `recoverWith(f, empty())`
* [x] `multicast`

### Operations that need more discussion

* `delay` - What is the _meaning_ of `delay(n, empty())`, especially wrt end?

### Related optimizations

Optimizations that don't produce canonical empty, but noting here so we don't lose them.

* `scan` - `scan(f, x, empty())` is `now(x)` rather than `empty()`. It's not clear whether this is a worthwhile optimization.

**Comment by Frikki** [comment]
Do we have a list (or a point in the direction where to spot those places)?

**Comment by briancavalier** [comment]
Nope.  We could start and maintain the list here in the original description, open a new PR for each item (or group of items), and check them off as we merge those PRs.  We'll just need to be a little careful about not letting this issue become one that stays open forever.

**Comment by briancavalier** [comment]
I added a list in the description.

**Comment by TylorS** [comment]
Couldn't `mergeArray` filter all streams out that are `empty()` ?

**Comment by briancavalier** [comment]
> Couldn't mergeArray filter all streams out that are empty() ?

Yep, and I think it should.  The natural extension of that is that if mergeArray ends up with an array of length zero after filtering out canonically empty streams, it should itself return a canonically empty stream.  When taken together with the fact that mergeArray already recursively flattens nested merge streams it encounters, mergeArray will be able to annihilate recursively.

**Comment by briancavalier** [comment]
All the boxes are checked 🎉 

Gonna close this, and we can handle any stragglers we may have missed in individual issues/PRs.
