### ISSUE TITLE
Start a FAQ

### ISSUE THREAD

**Issue by briancavalier** [mostjs/core#155]
An initial question we could answer:

* What is the relationship between `@most/core` and `most`?

Let's brainstorm a few others here.

**Comment by davidchase** [comment]
- Comparison with other libs ?
- How to use with Vdom libs like React
- How to use with Node callbacks

**Comment by Frikki** [comment]
* How do I produce and consume events from streams? (hint: synchronization)

**Comment by briancavalier** [comment]
Ok, I'm going to call this done, because we did _start_ a FAQ 😄 .  Thoughts on a good place to keep these questions that have been brainstormed here until we have a chance to write answers?
