### ISSUE TITLE
Suggestion: use ArrayLike for TypeScript Definitions

### ISSUE THREAD

**Issue by TylorS** [mostjs/core#156]
Currently all of our types specify `Array<A>` which disallows users to fully take advantage of types like `ReadonlyArray<A>` or `ArrayLike<A>` which, in TypeScript, both ensure that you can *not* mutate them.  However, because we are using `@most/prelude`, mutating arrays is avoided all together.

I think it would be very useful to update the types across each package switch 100% to `ArrayLike<A>`. This would be a non-breaking change as `ArrayLike<A>` is a subset of `ReadonlyArray<A>` which is a subset of `Array<A>`.

**Comment by Frikki** [comment]
I am all for that: generalization.

**Comment by briancavalier** [comment]
Great idea.  For Flow, we can use [`$ReadOnlyArray<A>`](https://github.com/facebook/flow/issues/3502#issuecomment-286259843).  I don't think Flow has an Array-like type, tho.

**Comment by TylorS** [comment]
@briancavalier should we include changes to the flow types in this issue, or open another?

**Comment by briancavalier** [comment]
@TylorS I think it makes sense to do TS and Flow in the same PR _unless_ it creates an overly messy PR, which is hard to imagine.

**Comment by TylorS** [comment]
Right on, just didn't know how you'd like to go about it. I'll soon then make a PR with both TS and flow type additions.

**Comment by Frikki** [comment]
Do we want this in most/core@1.0? Or is it post 1.0

**Comment by TylorS** [comment]
I think post is best.

**Comment by briancavalier** [comment]
I agree.  I feel like only things we agree are absolutely critical and require a breaking change should be candidates for 1.0 right now.  Since it's possible to do this in a non-breaking way, I added it to the [1.x backlog](https://github.com/mostjs/core/projects/4?).  If there's a compelling reason to do it before 1.0, though, let's talk about it!

**Comment by raveclassic** [comment]
Should be fixed in https://github.com/mostjs/core/pull/296
