### ISSUE TITLE
Remove timestamp()?

### ISSUE THREAD

**Issue by briancavalier** [mostjs/core#16]
Anyone use it regularly?  The only place it's used internally is in its own unit test.  Is there a compelling reason to keep it?

**Comment by davidchase** [comment]
cull it 🔪 but i think for every method or combinator we remove we should place a way to make it in the recipes guide, thoughts?

**Comment by briancavalier** [comment]
> every method or combinator we remove we should place a way to make it in the recipes guide

It sounds like a good idea, but do you mean combinators we remove from cujojs/most?  i.e. since the recipes wiki is in that repo.  Or do you think we should start another recipes wiki in this repo?

**Comment by davidchase** [comment]
yeah i think we can start one here... like a cookbook or something even

**Comment by TylorS** [comment]
Axe it :)

**Comment by davidchase** [comment]
stamp it ...`const timestamp = stream => stream.map(value => ({time: Date.now(), value}))` or something like that 🎉

**Comment by briancavalier** [comment]
> something like that

It's not quite that, since it should use the `scheduler`'s `now`.  If folks end up wanting something that gives them access to the event times, we may want to consider something like a "map with time" combinator (instead of creating an object like `timestamp()`):

```js
mapWithTime((t, x) => ..., stream)
```

**Comment by davidchase** [comment]
ah ok gotcha.. makes sense thanks
