### ISSUE TITLE
Remove the need to call PropagateTask's run function with `this`

### ISSUE THREAD

**Issue by briancavalier** [mostjs/core#19]
PropagateTask currently calls its run function [with itself as `this`](https://github.com/cujojs/most/blob/master/src/scheduler/PropagateTask.js#L34).  This was an easy (but not simple) way to provide access to the `active` state, which is needed to stop early in the case where the task is canceled due to any of the various ways the stream could be disposed, such as `take()`.

That leads to WTFs like [where does `this.active` come from?!?](https://github.com/cujojs/most/blob/master/src/source/fromArray.js#L21).  It would be nice to find a better solution.

**Comment by TylorS** [comment]
Could we just explicity pass a function of sorts?

```js
PropagateTask.prototype.run = function (t) {
  if (!this.active) {
    return
  }
  const run = this._run;
  run(t, this.value, this.sink, () => this.active)
}
```

Would this have a large impact on performance?

Then inside of `fromArray` for example

```js
function runProducer (t, array, sink, isActive) {
  for (var i = 0, l = array.length; i < l && isActive(); ++i) {
    sink.event(t, array[i])
  }

  this.active && end(t)

  function end (t) {
    sink.end(t)
  }
}
```

**Comment by davidchase** [comment]
does `isActive` need to be in a closure? or could we simply pass in the bool?

**Comment by TylorS** [comment]
If we were to pass the value directly we would lose the correct reference and thus the possibility of it changing over time.

**Comment by briancavalier** [comment]
An alternative to a closure would be to pass the task itself as the final arg:

```js
PropagateTask.prototype.run = function (t) {
  if (!this.active) {
    return
  }
  const run = this._run;
  run(t, this.value, this.sink, this)
}
```

That makes `this.value` and `this.sink` slightly redundant.  On the upside, though, they are the things you'll care most about, and if you want to ignore the 4th argument, you can do so easily.  We could still add an `isActive()` method if we wanted to say that the `active` *property* is an implementation detail.

**Comment by TylorS** [comment]
Either or is cool to me
