### ISSUE TITLE
Mostjs v2 discussion

### ISSUE THREAD

**Issue by jadbox** [mostjs/core#191]
redux-most refers to this repo for checking out a preview of Most 2, although I'm not what I'm suppose to see here. Does mostjs/core:master constitute Most 2... is there v2 discussions somewhere?

redux-most readme:
```
Most 2.0 will be even better, as it will feature an auto-curried API like lodash/fp and ramda, but for working with streams instead of arrays. For a preview of what's to come, check out what's going on here. https://github.com/mostjs/core
```

**Comment by briancavalier** [comment]
Hey @jadbox.  Thanks for the kind words in the redux-most README 😄 

As of right now, mostjs/core probably will not fully constitute most 2.0.  However, most 2.0 will definitely be built upon mostjs/core.  One possibility is that most 2.0 will be a relatively thin "batteries included" layer.

In any event: Most 2.0 and mostjs/core will be compatible and interoperable.

We'd be happy to answer specific questions as best we can in gitter, with the understanding that some things have yet to be decided.  Once a few more things have been nailed down, and/or there's some code (e.g. a prototype or alpha) around which to formulate discussions on GitHub, an issue thread will probably be good.  We don't an ETA on that yet, though.

**Comment by briancavalier** [comment]
@jadbox there's more ongoing discussion in [gitter](https://gitter.im/cujojs/most).  I think that's the better forum until there's some actual code in a repo around which to discuss, so I'll close this.

The current proposal is for most 2.0 simply to be `@most/core`.  We'd love your feedback in gitter!
