### ISSUE TITLE
Bug: `seedValue.d.ts` has a lot of leftover base types

### ISSUE THREAD

**Issue by hoichi** [mostjs/core#212]
Inside `seedValue.d.ts` there are numerous base types: `Sink`, `Scheduler` &c.

Except for the `SeedValue` itself, no other exported type seems to be used anywhere: the correct types are imported from `@most/types`. Still, they can confuse an IDE into suggesting them if you don’t have `@most/type` installed.

**Comment by briancavalier** [comment]
Thanks @hoichi.  Seems like a simple matter of deleting the leftovers.  We'll take a look soon.
