### ISSUE TITLE
Flow, Typescript or plain Javascript for code repository

### ISSUE THREAD

**Issue by nikoskalogridis** [mostjs/core#233]
Wondering if you have discussed/decided on whether the code base should be in plain Javascript as it is now or amended with Flow types or migrate to Typescript.

My personal opinion would be to switch to using Flow types. 

Advantages:
- Keeping the current build stack (babel, rollup) intact
- Completely static type check all the files in the code base
- Gradually migrate files (without renaming all of them in .ts)
- If we decide to change this decision and revert to plain Javascript we can simply strip the Flow types from the files and be done with it
- If we decide to switch to Typescript at some time in the future that will be easier as we would already have made most of the work required. We would only need to change some incompatibilities between Flow and Typescript.

I would be interested to hear what the members think on this

**Comment by briancavalier** [comment]
Hey @nikoskalogridis. This is being discussed in #219.  Please feel free to add your comments there.
