### ISSUE TITLE
Documentation and example on how resource disposion works

### ISSUE THREAD

**Issue by ftaiolivista** [mostjs/core#265]
Hi. Would be great to have documentation and example on how resource disposion works.

How and when most.js unsubscribe from DOM elements?

**Comment by briancavalier** [comment]
Hi @ftaiolivista, thanks for asking.  I agree we need a bit more info about disposal timing.  It is well-defined, though, and I'll try to provide a bit of general info here.

In the general case, there are 2 things that determine when disposal happens:

1. Producers may initiate disposal when they have no more events to produce.  This case is specific to each producer.  For example, [most/dom-event](https://github.com/mostjs/dom-event) producers are infinite and will never initiate disposal, but [now](https://mostcore.readthedocs.io/en/latest/api.html#now) disposes immediately after producing its only event.
2. Combinators such as [take](https://mostcore.readthedocs.io/en/latest/api.html#take) and [until](https://mostcore.readthedocs.io/en/latest/api.html#until) allow you declare which events you are interested in.  These arrange for disposal to occur after all the events you're interested in have occurred.

In general, for any most/core event stream, both of these factors may be in play.  Disposal will happen at the earliest of these factors.  For example `take(2, now('hi'))` disposes immediately after 1 event, and `take(2, periodic())` disposes immediately after 2 events.

I hope that helps to provide context ... and potentially helps to answer your question.  As for DOM elements, specifically, most/core itself doesn't deal with DOM events.  Can you be a bit more specific about the particular use case you're asking about?  That would help us provide a more detailed for your particular situation.  For example, maybe you are using [most/dom-event](https://github.com/mostjs/dom-event)?
