### ISSUE TITLE
Distribute a bundled version for browser consumption

### ISSUE THREAD

**Issue by louy2** [mostjs/core#267]
Today I wanted to try out mostjs and followed instructions here, and was happy to see you offering a ES6 module version, so I tried to `import` directly from `https://unpkg.com/@most/core@1.3.2/dist/index.es.js`. Unfortunately because `@most/core` `import`s `@most/prelude` in that file using a packager, while the browser can't find the `@most/prelude`, I couldn't use it. I looked further and found no documentation on how to use `@most/core` without a packager. Is it not supported?

**Comment by briancavalier** [comment]
Hi @louy2.  Unpkg requires adding `?module` at the end of urls in order to load ES modules.  See the "Query Parameters" section here: https://unpkg.com.

So, for example, you can use a module script tag like:

```html
  <script type="module">
    import { now } from 'https://unpkg.com/@most/core?module'
  </script>
```

Cheers!

**Comment by louy2** [comment]
Thank you so much!
