### ISSUE TITLE
Is there an equivalent operator of RxJS's exhaustMap?

### ISSUE THREAD

**Issue by gitusp** [mostjs/core#279]
I'm migrating to Most from RxJS and wondering if there's an equivalent operator of RxJS's `exhaustMap` on Most. If there's no equivalent operators, I'd like to implement that and add it to https://github.com/mostjs-community.
(I believe the behavior of `exhaustMap` can not be implemented by combining the existing operators. Correct me if I'm wrong.)

Anyway thank you for hosting such a great project! I immediately fell in love with Most's API.

**Comment by briancavalier** [comment]
Hi @gitusp, thanks for the kind words.  I'm glad you've found most's API to be intuitive.

You're right that there's no equivalent to RxJS's exhaustMap, and we'd certainly welcome your contribution to mosts-community.  [Here's how you can become a member and start contributing](https://github.com/mostjs-community/about#getting-involved).

**Comment by gitusp** [comment]
@briancavalier Thanks for your instruction. I've read it and will follow it.
Since my question is resolved, I close this issue.
