### ISSUE TITLE
memoryStream

### ISSUE THREAD

**Issue by ftaiolivista** [mostjs/core#280]
Hi. Is there a way to have something like  [Xstream memoryStreams](https://github.com/staltz/xstream#memorystream) with Most core?

My problem is:

1 - Event X happen on stream A
2 - A new component is created as stream A sinks
3 - The component add new stream B dependent on stream A
4 - I want something to happen on stream B based on event X (or well, the last event on stream A). But the stream B was added when event X is already passed. 

I think I could use startWith and pass event X data to stream B. But having a memoryStream like xstreams may help to bypass making all event data visibile to the new created componet.

**Comment by davidchase** [comment]
Hi @ftaiolivista
It seems like you are looking for something like https://github.com/mostjs/hold ?
Let me know if this helps or if I missed something entirely not that familiar with xstream

**Comment by ftaiolivista** [comment]
@davidchase  Yes. Hold it's what I was looking for. Thank you :))
