### ISSUE TITLE
Utilizing "join" to flatten stream?

### ISSUE THREAD

**Issue by scoobyshi** [mostjs/core#282]
I am attempting to leverage Most/Core (and most-from-event) to stream Web Socket events (utilizing Socket IO), and am curious how to utilize join appropriately to expose an inner stream.  

So, in the old documentation for Most, it described something like this (ref: https://github.com/cujojs/most/wiki/Concepts#higher-order-streams):

```
const firstClick = most.fromEvent('click', document).take(1);
const mousemovesAfterFirstClick = firstClick.map(() =>
	most.fromEvent('mousemove', document)
		.takeUntil(most.of().delay(5000)))
```

could be written as:

```
// join() "flattens" a higher order stream
mousemovesAfterFirstClick.join()
	.observe(console.log.bind(console));
```

Now, the Most/Core API is different obviously from the original implementation, so I'm wondering how this would be done now?  I understand you can utilize "runEffects" and "tap" for example to achieve something like ".observe", but wasn't sure about join (I didn't see anything in the examples or docs, except a definition, but not an example like above).

Specifically, I have this example (leveraging most-from-event and Most/Core):

```
const ioStream = fromEvent('connection', io);
const connEventHandler = socket => {
  console.log('Connection via Socket, ID:', socket.id);
  const socketStream = fromEvent('message', socket);
  const renderSocket = message => console.log('Socket event:', message);
  runEffects(tap(renderSocket, socketStream), newDefaultScheduler());
};
runEffects(tap(connEventHandler, ioStream), newDefaultScheduler());
```

And this works fine, but would be interested in surfacing the "message" events (maybe join isn't the best approach?)...

**Comment by scoobyshi** [comment]
Actually, maybe I figured it out, this appears to do what I need, silly me, I was getting an error trying to join(ioStream) because of course it wasn't returning a stream, so this now works:

```
const onlySocketMessage = map(socket => fromEvent('message', socket), ioStream);
const flatSocketMessage = join(onlySocketMessage);
const renderSocketMessage = event => console.log('Socket Message:', event);
runEffects(tap(renderSocketMessage, flatSocketMessage), newDefaultScheduler());
```

Next will be to see if I can skip using most-from-event and create my own Stream.

**Comment by briancavalier** [comment]
Hey @scoobyshi, glad you worked through it. Thanks for giving `@most/core` a try. Cheers!
