### ISSUE TITLE
Duplicate addition of offset time to local time on `switch`?

### ISSUE THREAD

**Issue by gitusp** [mostjs/core#284]
On https://github.com/mostjs/core/blob/master/packages/core/src/combinator/switch.js#L113, `this.min` seems to end up being added to inner's local time twice when the inner `Segment` receives `end` or `error`.

---

At first, `this.min` is added to its local time on:
- https://github.com/mostjs/core/blob/master/packages/core/src/combinator/switch.js#L105
- or
- https://github.com/mostjs/core/blob/master/packages/core/src/combinator/switch.js#L109

Then, the method calls outer's `_disposeInner`, and it eventually goes into inner's `_dispose`, which adds `this.min` to local time again.

I'm sorry that I have not tested it.
But if the concern is true for you too, I'll write a test and open a PR for it.
Thank you.

**Comment by briancavalier** [comment]
Hi @gitusp.  Thanks for opening an issue for this.  It does indeed look like a bug, and we'd very much appreciate a PR, especially one that starts with a failing test, as you mentioned.

Thanks!

**Comment by gitusp** [comment]
@briancavalier Thank you for checking out the issue. I'll give a shot soon.
