### ISSUE TITLE
Tight coupling to Time

### ISSUE THREAD

**Issue by krzysztofpniak** [mostjs/core#422]
I'm wondering why the library strongly relies on time. Imagine the case of dom clicks event stream. 
There is no need to introduce concept of time. Another example is the stream of sequential file read. I think time related functions should relies on time. Proposal of the simplified API:
```
runEffects :: Stream a -> Promise void
periodic :: Scheduler -> Period -> Stream void //order of params prepared for partial application of the common scheduler
at :: Scheduler -> Time -> a -> Stream a
```
Please correct me if I miss something.

**Comment by Frikki** [comment]
@krzysztofpniak , an event is a time-value pair. That is, the value is emitted on a specific time. This is indeed true for a sequence of DOM clicks.

**Comment by Frikki** [comment]
I want to add that the [Most architecture treats everything asynchronously](https://mostcore.readthedocs.io/en/latest/concepts.html#always-async).  Tasks are managed by `Schedulers`, which provide a central notion of time for the `Streams`. I would suggest you to [read about `Schedulers`, `Time`, `Tasks` and `TimeLines`](https://mostcore.readthedocs.io/en/latest/api.html#most-scheduler).

**Comment by krzysztofpniak** [comment]
@Frikki I've read the whole docs before I created this issue. I still don't understand why event is the time-value pair. Are you using timestamps of DOM clicks internally?

**Comment by Frikki** [comment]
A stream is a serious of values over time. For examples:

```
stream: abc-def->
```

- `a` occurs at time 0, `b` at time 1, and `c` at time 2,
- no events occur at time 3,
- `d` occurs at time 4, `e` at time 5, and `f` at time 6,
- no events occur at time 7,
- the pattern continues infinitely, repeating a similar pattern.

As you have already read the docs, it may be a mute point to re-iterate, but for good measure:

> An _event_ is a value that _occurs_ at a particular instant in time. For example, a mouse click is an event.
> 
> Conceptually, you can think of an event as a (time, value) pair, where the event’s time is just as important as its value. You can’t know the value of a mouse click until the mouse button actually is clicked.

This explains why an event is a time-value pair.

> An _event stream_ is a time-ordered sequence of events. For example, all the mouse clicks in a document can be represented as an event stream.
>
> Conceptually, you can think of an event stream as an array of (time, value) pairs. However, whereas an array is ordered by index, an event stream is ordered by its events’ occurrence times. You can’t observe the second mouse click until after you’ve observed the first one.
>
> Event streams may be _infinite_, _finite_, or may _fail_.

I hope that explains.

**Comment by Frikki** [comment]
I forgot to address this question:

> Are you using timestamps of DOM clicks internally?

Yes. The type `Time` is an essential part of `Schedulers`. It is an instance in time, which can be a world-clock time or virtual time, depending on the `Scheduler` in use.  You can check [the scheduler package’s source files](https://github.com/mostjs/core/tree/a4f66cb5ef15150151e4255454a37d64bb693717/packages/scheduler/src) to see how `Time` is used. For example, see how [`clock`](https://github.com/mostjs/core/blob/a4f66cb5ef15150151e4255454a37d64bb693717/packages/scheduler/src/clock.ts) is implemented.

**Comment by semmel** [comment]
> Imagine the case of dom clicks event stream. There is no need to introduce concept of time.

Indeed, with such a source like dom events, the *exact* physical time of origin is irrelevant since it is not accessible anyway in browsers which just expose low precision timers. (The time resolution is a ridiculously coarse 1msec on CPUs with a GHz clock rate.) 

Nevertheless it is valuable for a reactive library to align dom events *not* just in a time-independent sequence but to assign something time-related with the events. 
How else would you combine time effects like rate limiting then?
```javascript
throttle(50, click(button))
```
