### ISSUE TITLE
Atomic updates with triangle-shaped data flow

### ISSUE THREAD

**Issue by semmel** [mostjs/core#443]
Does most support atomic combine updates in a re-joining data flow graph?
```javascript
/*
   ->p-> 
 /       \
n       p · q --> ?
 \        /
   ->q->
*/
const id = x => x;
const add = (a, b) => a + b;

var n = multicast(continueWith(() => now(2), now(1)));
var p = map(id, n);
var q = map(id, n);

var pq = combine(add, p, q); // -> 2, 3, 4

// EXPECTED: 2, 4
```
See [demo on RunKit](https://runkit.com/semmel/diamond-shaped-combine)

**Comment by briancavalier** [comment]
Hi @semmel, good question.  As you observed, mostjs isn't transactional.  Additionally, simultaneous events will have equal time values, but propagated in some order.

There are techniques that can help, such as using products (tuples and records).  I did some experiments with it [here](https://github.com/briancavalier/most-product).

If you need transactional updates, though, mostjs may not be the best choice.

Hope that helps.  I'll close this issue, but please feel free to continue the discussion if you have follow questions.  Cheers!

**Comment by semmel** [comment]
Thank your for your quick answer @briancavalier,
>If you need transactional updates, though, mostjs may not be the best choice.

I use frp streams to collect the *UI state* in the browser (something similar to the React-Redux flow). When I update the DOM on changes im my UI state I *debounce* those events anyway, so in that use case I would not need atomicity. 

Also, as someone else noticed, as long as the functions in the frp pipeline are *pure*, those extra events do not matter (except perhaps performance-wise).

So one could conclude, that one should always debounce side-effects? 🤔

**Comment by briancavalier** [comment]
I think ultimately the answer is "it depends" (as usual).  For example, if the side effect is just simple UI updates, it may not matter, but if it's sending text messages, it may!  Debouncing is definitely a helpful tool for some situations.  Sampling can also be quite helpful.

I guess the overall takeaway is that side effects still require some care.  Libraries can help us manage them, but no library frees us entirely.
