### ISSUE TITLE
TS typings: improve typesafety of Stream<T> interface

### ISSUE THREAD

**Issue by Nedgeva** [mostjs/core#605]
**The problem:**
right now it is possible to assign value of type ```Stream<unknown>``` to value with almost any other type argument of ```Stream<T>```.

**Minimal example to reproduce:**
```typescript
let s1: Stream<number> = now<number>(1)
const s2: Stream<unknown> = now<unknown>('s')
s1 = s2; // no error here, inferred type is still Stream<number>
```
In real-life complex scenarios this behavior may lead to potentially unsafe code.
This happens because ts compares only signature of ```run``` method inside ```Stream<T>``` intreface.

For my personal project i did managed to solve this by using custom ```Stream<T>``` interface with optional property of type ```T```, but i'm pretty sure that there are better options.

**Comment by TylorS** [comment]
Hey @Nedgeva! Thanks for the example, we can tell that it has to do with `Sink<T>` being in a contravariant position. I'm guessing your local version is also something like the following, right? I don't know of any other way besides changing our API to place `T` in a covariant position like a return type. @Frikki and I discussed it and we would be willing to accept this change to our TS types

```ts
interface Stream<T> {
  _T?: T
  ...
}
```

**Comment by Nedgeva** [comment]
> I'm guessing your local version is also something like the following, right?

Exactly!

> @Frikki and I discussed it and we would be willing to accept this change to our TS types

Thanks! Will open PR, but should we mark optional `_T` property as quasi-private (e.g. via `Symbol` or using something different techniques) to prevent accidental messing when extending `Stream` interface or it's just redundant?
