### ISSUE TITLE
I can't get `during` to work with window streams created using `until`

### ISSUE THREAD

**Issue by micahscopes** [mostjs/core#657]
I'm having trouble using `during` with a time window stream created using `until`.  This works fine:
```js
periodic(1)
|> during(
  at(0, at(5))
) ...
```
however using various window streams derived from `until` doesn't seem to work for me:
```js
periodic(1)
|> during(
  never() |> until(at(5))
) ...
```

**Comment by TylorS** [comment]
Hey @micahscopes, I think the key difference between the first and second example is the first creates a higher-order stream (a stream of streams) whereas the second example does not. During utilizes the higher-order nature to determine when to start subscribing (when the "inner" stream has been emitted) and then when to stop when the "inner" stream has emitted its own value.

I hope that helps to understand the difference

**Comment by micahscopes** [comment]
Oh wow... that makes sense, and yes that did it.  I changed the second example to the following and it worked as intended:
```
periodic(1)
|> during(
  never() |> until(at(5)) |> now
) ...
```
