### ISSUE TITLE
TypeError calling performance.now

### ISSUE THREAD

**Issue by frangio** [mostjs/core#69]
I mentioned it in [a comment](https://github.com/mostjs/core/pull/63/files#r120018903) in a closed PR so I'm opening an issue here.

The `performance.now` method is being called as a function without binding `this` to `performance` and it's causing an error. I guess this wasn't detected in testing because the tests run in a node.js environment?

**Comment by davidchase** [comment]
@frangio thanks for reporting this... i guess its not bound in browsers we will update unless you want to send in a PR?
