### ISSUE TITLE
multicast

### ISSUE THREAD

**Issue by axefrog** [mostjs/core#83]
Should multicast go in core? I can modify the implementation and provide a pull request if so.

**Comment by davidchase** [comment]
hey @axefrog i started it here #77 just haven't had time to pull in the code from multicast back into the core and fix the issue.

if you have time and need it rather quickly i think you can go ahead with the PR.

/cc 
@briancavalier @TylorS

**Comment by davidchase** [comment]
#77 just got merged so i think this is safe to close

**Comment by briancavalier** [comment]
👍

**Comment by axefrog** [comment]
Nice work! Sorry, I get so busy with my own work that my intended contributions sometimes become casualties of the passage of time...

**Comment by davidchase** [comment]
No worries try it out we published it today as well let us know 😎

**Comment by axefrog** [comment]
Yep I have updated my deps. Will let you know if I encounter any issues.
