### ISSUE TITLE
Will this work with Cycle.js?

### ISSUE THREAD

**Issue by mjleitch** [mostjs/core#89]
Just wondering if core can be used interchangeably with @cycle/most-run? or if it's best to stick with the main most library for now?

FYI... Definitely liking the direction you're taking most ...towards a more classical frp approach (i.e. continuous time, behaviors, etc). Excited for what's to come!

**Comment by axefrog** [comment]
Check out @TylorS' [Motorcycle](https://github.com/motorcyclejs/motorcyclejs) framework, which is an adaptation of Cycle.js built around Most.js, with some other enhancements too.

**Comment by mjleitch** [comment]
ohh... my understanding was that Cycle.js union was a collaborative effort to bring the two projects together. Didn't realize Motorcycle was still an active project in its own right. I'll definitely revisit. Thanks @axefrog!

**Comment by TylorS** [comment]
Currently Cycle.js does not support `@most/core` as it's not reached v1 yet. `Motorcycle` has become more of it's own project and no longer tries to be 1:1 with Cycle as it was in the beginning (expect more and more differences in the future) but also does not yet support `@most/core`, but that work will be done in due time.

**Comment by mjleitch** [comment]
Great Thanks for the insight @TylorS.

**Comment by TylorS** [comment]
@mjleitch Just wanted to let you know https://github.com/motorcyclets/motorcycle is 100% `@most/core` ready now!

**Comment by mjleitch** [comment]
@TylorS- Ha! I just stumbled across the latest a couple hours ago! I have a couple questions... but they seem more appropriate for [gitter](https://gitter.im/cujojs/most), so I'll hit you up in there. Thanks!
