### ISSUE TITLE
What to do with sample, sampleWith?

### ISSUE THREAD

**Issue by briancavalier** [mostjs/core#9]
Since `@most/sample` exists as a "better" sampling implementation, what should we do with the existing `sample` and `sampleWith` functions in `@most/core`?

Some possible options:

1. Keep them as is.  I'm not sure why we would do this.  Are there any compelling reasons?
1. Keep them as exports, but reimplement them using `@most/sample`.  I can't think of a compelling reason to do this, since `@most/core` has no backward compatibility concerns.
1. Remove them and direct people to `@most/sample`
1. Deprecate `@most/sample`, and integrate its API and implementation directly into `@most/core`.  If we did this, we'd still need to decide whether to keep the existing `sample` and `sampleWith`.  If we kept them, I can't see a reason *not* to reimplement them.

I don't have a sense for how often they are used, which may be a factor: if they're common, then people would always find themselves needing both `@most/core` and `@most/sample` that's an interesting data point that could push us in the direction of 4 rather than 3.

Thoughts?

**Comment by TylorS** [comment]
I'm in favor of number 4 actually, I do use `sampleWith` quite often.

**Comment by briancavalier** [comment]
Cool, thanks @TylorS.  Another thing I like about number 4 is that it reduces repository maintenance.

**Comment by briancavalier** [comment]
I'm about to do 4 😄 which means we need to deal with the secondary decision: "whether to keep the existing sample and sampleWith".

My current leaning is *not* to keep them in `@most/core`, but rather to reimplement them in `cujojs/most`.  How does that sound?
